apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: computers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Naveen-cloud-DevOps/google-store-DevOps-project.git
    targetRevision: main
    path: frontend/computers/
  destination:
    server: https://kubernetes.default.svc
    namespace: google
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
